### ISSUE TITLE
url spot not displaying after Back

### ISSUE THREAD

**Issue by Habbie** [myano/lmddgtfy#1]
When I use the back-button to go back to lmddgtfy.net, my search text is still in the input box but the URL below it does not display until I edit my search text.

**Comment by KK4OXJ** [comment]
@myano Yes, it is possible. I'm trying to clear some copyright permissions before I put the code for my version of LMDDGTFY on GitHub, but once it's up, I'll show you. Or I could just post the code in a comment, if you really want to know.

**Comment by myano** [comment]
After the new-redesign, the search is completely lost when going back a page to lmddgtfy. :-\

**Comment by KK4OXJ** [comment]
@myano I've fixed that in my local version, I'll submit a PR soon that will fix a few issues.

**Comment by myano** [comment]
@KK4OXJ Awesome, thanks! :+1:

**Comment by myano** [comment]
@KK4OXJ If you can remember to mention "#1" in the git commit, that'd be fantastic. (That way it'll show up in this issue history.) Thank you again. :-)

**Comment by KK4OXJ** [comment]
Maybe this could be closed now? @myano
